(** Typed helpers for the Valkey Bloom module.

    Bloom filters are probabilistic sets: [exists] returning [false]
    means the item is definitely absent, while [true] means it may be
    present according to the filter's configured false-positive rate.

    Commands route by filter key, so they work correctly in cluster
    mode as long as applications use the same hash-slot rules as other
    Valkey key commands. *)

type scaling =
  | Default_scaling
  | Expansion of int
  | Non_scaling
(** Creation scaling mode. [Default_scaling] uses the module
    defaults, [Expansion n] sends [EXPANSION n], and [Non_scaling]
    sends [NONSCALING]. *)

type insert_options = {
  capacity : int option;
  error_rate : float option;
  scaling : scaling;
  seed : string option;
  tightening : float option;
  validate_scale_to : int option;
  no_create : bool;
}
(** Options for [BF.INSERT]. [seed] is passed through as-is; Valkey
    validates the module's 32-byte seed requirement. [Non_scaling]
    and [validate_scale_to] are mutually exclusive and raise
    [Invalid_argument] before a command is sent. *)

val default_insert_options : insert_options

val reserve :
  ?timeout:float ->
  ?scaling:scaling ->
  Client.t ->
  key:string ->
  error_rate:float ->
  capacity:int ->
  (unit, Connection.Error.t) result
(** [BF.RESERVE key error_rate capacity]. *)

val add :
  ?timeout:float ->
  Client.t ->
  key:string ->
  string ->
  (bool, Connection.Error.t) result
(** [BF.ADD]. Returns [true] when the item was newly added and
    [false] when it was already present according to the filter. *)

val madd :
  ?timeout:float ->
  Client.t ->
  key:string ->
  string list ->
  (bool list, Connection.Error.t) result
(** [BF.MADD]. Empty item lists raise [Invalid_argument]. *)

val exists :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  string ->
  (bool, Connection.Error.t) result
(** [BF.EXISTS]. [false] means definitely absent; [true] can be a
    probabilistic positive. *)

val mexists :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  string list ->
  (bool list, Connection.Error.t) result
(** [BF.MEXISTS]. Empty item lists raise [Invalid_argument]. *)

val insert :
  ?timeout:float ->
  ?options:insert_options ->
  ?items:string list ->
  Client.t ->
  key:string ->
  (bool list, Connection.Error.t) result
(** [BF.INSERT]. When [items] is omitted or empty, the command creates
    or validates the filter and returns an empty list. *)

val card :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  (int, Connection.Error.t) result
(** [BF.CARD]. Missing filters return [0]. *)

type info = {
  capacity : int;
  size : int;
  filters : int;
  items : int;
  error_rate : float;
  expansion : int option;
  tightening : float option;
  max_scaled_capacity : int option;
  raw : (string * Resp3.t) list;
}
(** Parsed [BF.INFO] payload. Fields that do not apply to
    non-scaling filters are [None]. [raw] preserves the full server
    payload for forward compatibility with newer valkey-bloom
    versions. *)

type info_selector =
  | Capacity
  | Size
  | Filters
  | Items
  | Error_rate
  | Expansion_rate
  | Tightening_ratio
  | Max_scaled_capacity

type info_value =
  | Int of int
  | Float of float
  | Not_applicable

val info_raw :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  ((string * Resp3.t) list, Connection.Error.t) result
(** Raw [BF.INFO] key/value pairs. *)

val info :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  (info, Connection.Error.t) result

val info_value :
  ?timeout:float ->
  ?read_from:Client.Read_from.t ->
  Client.t ->
  key:string ->
  info_selector ->
  (info_value, Connection.Error.t) result
(** [BF.INFO key selector]. *)

val load :
  ?timeout:float ->
  Client.t ->
  key:string ->
  dump:string ->
  (unit, Connection.Error.t) result
(** [BF.LOAD]. This is mainly generated by Valkey during AOF rewrite,
    but exposing it keeps the typed surface complete. *)

module For_testing : sig
  val reserve_args :
    scaling:scaling ->
    key:string ->
    error_rate:float ->
    capacity:int ->
    string array

  val insert_args :
    options:insert_options ->
    key:string ->
    items:string list ->
    string array

  val info_args : ?selector:info_selector -> key:string -> unit -> string array
  val decode_bools : string -> Resp3.t -> (bool list, Connection.Error.t) result
  val decode_info_raw : Resp3.t -> ((string * Resp3.t) list, Connection.Error.t) result
  val decode_info : Resp3.t -> (info, Connection.Error.t) result
  val decode_info_value : info_selector -> Resp3.t -> (info_value, Connection.Error.t) result
end
